version: '3.3'

services:
  postgres:
    container_name: postgres
    image: postgres:16.3
    environment:
      POSTGRES_DB: "main"
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "root"
    ports:
      - "5432:5432"

  redis:
    container_name: redis
    image: redis:7.4.0
    restart: always
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=root
      - REDIS_PORT=6379
